[application]

[web.app]

# HTML title tag content
title = "dAGIT Builder"

# include `assets` in web platform
[web.resource]


[web.watcher]
reload_html = true
watch_path = ["src", "public", "../../packages"]


# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
